guardian/giant

README.md

Was previously relative, this makes it absolute so it goes to the right place..

Fix icij/datashare url that was 404ing

---

backend/app/extraction/ocr/OcrMyPdfExtractor.scala
backend/app/extraction/ocr/OcrMyPdfImageExtractor.scala
backend/app/utils/Ocr.scala

We have seen out of space errors with big PDFs in production, presumably because it is using /tmp on the small root EBS volume rather than the larger data volume we create.
Following the advice from https://github.com/jbarlow83/OCRmyPDF/issues/560.

Set TMPDIR for OCRmyPDF to scratch space

---

backend/app/extraction/ocr/OcrMyPdfExtractor.scala
backend/app/extraction/ocr/OcrMyPdfImageExtractor.scala
backend/app/utils/Ocr.scala

Follow up to #3 which set `TMPDIR` for OCRmyPDF:
- Remove `Uri( )` toString wrapper from temporary file name
- Write the output PDF to the same scratch directory we pass as `TMPDIR`

OCR temp folder fixes

---

backend/app/AppComponents.scala
backend/app/extraction/ocr/BaseOcrExtractor.scala
backend/app/extraction/ocr/ImageOcrExtractor.scala
backend/app/extraction/ocr/OcrMyPdfExtractor.scala
backend/app/extraction/ocr/OcrMyPdfImageExtractor.scala
backend/app/extraction/ocr/TesseractPdfOcrExtractor.scala
backend/app/utils/Ocr.scala

Other OCR extractors catch the subprocess dying (such as during a Riff-Raff deploy) and don't mark it as a failure so the work can be picked up by a future worker. Unfortunately we didn't include this behaviour for the OCRmyPDF extractors. This PR adds it back in a base class to try and make it less likely we regress this again. Ideally we'd have integration tests for it too but this is a decent first step.
It also adds incremental logging for stderr of the subprocess. Before we only logged once everything was complete and it was impossible to get a sense of how far through OCRing a very large PDF we were.
Bonus feature, the last stderr log line is passed through the client as a progress note:
https://user-images.githubusercontent.com/395805/119389744-ed407080-bcc3-11eb-8fe6-9413d1a0bab5.m …

Incremental OCR logging and retry OCR after deploy (again)

---

backend/app/extraction/Worker.scala

Without this you have to dig back through the logs for a particular worker instance to find the corresponding "Working on XYZ" log message. For big OCR jobs this could be hours ago.

Log blob URI in extractor failure

---

backend/app/utils/auth/AuthActionBuilder.scala
backend/test/utils/auth/AuthActionBuilderTest.scala

We shouldn't alarm on "failed to parse token", since this happens whenever the token is missing, as a result of vulnerability scanners and occasionally developer testing/debugging (e.g. just opening https://giant.pfi.gutools.co.uk/api/search in your browser will fire this alarm). We get spurious alarms most weeks because of this

Do not alarm on failure to parse token

---

backend/app/utils/aws/S3Client.scala

Following from https://github.com/guardian/pfi/pull/924 and a recent error on PROD when trying to upload a file to giant, this makes sure that post putObject the input stream for the object gets closed.
UPDATE: Sadly, this function is never actually called so can't be responsible for the issue. Probably worth fixing though in case we use it in future
Here's the stacktrace from earlier today
```
AWS Sdk Failure: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHt …
```

Always close s3 client in putObjectSync

---

frontend/src/js/components/viewer/DocumentMetadata.js

I *think* these links should've changed when we upgraded to ES 7
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
> **Elasticsearch 7.x**
> Specifying types in requests is deprecated. For instance, indexing a document no longer requires a document type. 
> The new index APIs are PUT {index}/_doc/{id} in case of explicit ids and POST {index}/_doc for auto-generated ids. : > Note that in 7.0, _doc is a permanent part of the path, and represents the endpoint name rather than the document type.*

Correct es link in dev tools

---

backend/app/utils/Ocr.scala

We started using `--redo-ocr` in order to preserve original machine-readable text in a documents that contained it (rather than re-OCR-ing everything).  See https://github.com/guardian/pfi/pull/929, https://github.com/guardian/pfi/pull/893
However, here is https://ocrmypdf.readthedocs.io/en/latest/errors.html?highlight=redo-ocr#page-already-has-text:
> - `ocrmypdf --force-ocr` to rasterize all vector content and run OCR on the images. This is useful if a previous OCR program failed, or if the document contains a text watermark.
> - **`ocrmypdf --skip-text` to skip OCR and other processing on any pages that contain text. Text pages will be copied into the output PDF without modification.**
> - `ocrmypdf --redo-ocr` to scan the file for any existing OCR (non-printing text), remove it, and …

--skip-text not --redo-ocr

---

backend/app/AppComponents.scala
backend/app/extraction/Worker.scala
backend/app/ingestion/phase2/IngestStorePolling.scala
backend/app/services/MetricsService.scala
backend/app/utils/controller/FailureToResultMapper.scala
backend/test/extraction/WorkerTest.scala

We recently performed a large ingest on giant. This resulted in a lot of alarms. The majority of these were triggered by the failuretoresultmapper metric - which alarms whenever there's more than 1 error. The link between worker errors and failuretoresultmapper was added in https://github.com/guardian/pfi/pull/925 in order to alarm when workers fail. However, grouping frontend errors (e.g. auth failure 5xx/4xx errors) that users experience with ingest errors isn't very helpful when it comes to setting a threshold for triggering an alarm on - as we have a small number of users we want to be notified for every time a user hits an error, but we don't want an alarm when, during a 10,000 file ingest there is a single failure.
This PR disconnects the workers from failuretoresultsmapper and …

Add new metrics for ingest failures

---

build.sbt

Welcome to the JVM!
Doing a quick dependency tree check it looks like the only non-2.15.0 versions of log4j are excluded.
```
user@ubuntu:~/code/pfi/giant$ sbt coursierDependencyTree | grep log4j
├─ org.apache.logging.log4j:log4j-api:2.15.0
├─ org.apache.logging.log4j:log4j-core:2.15.0
│  └─ org.apache.logging.log4j:log4j-api:2.15.0
├─ org.apache.logging.log4j:log4j-to-slf4j:2.15.0
│  ├─ org.apache.logging.log4j:log4j-api:2.15.0
│  │  ├─ (excluded) log4j:log4j:1.2.17
│  │  └─ (excluded) org.slf4j:slf4j-log4j12:1.7.21
```

Bump Log4j Version

---

build.sbt

Upgrading log4j to 2.16.0 which is the latest recommendation.
More information: https://logging.apache.org/log4j/2.x/security.html

Upgrade log4j to version 2.16.0

---

build.sbt

Another log4j vulnerability has been identified - this one is high severity (instead of critical) but we should still upgrade within 14 days.
The version we're on (2.16) doesn't protect us from infinite recursion in lookup evaluation, meaning intentional recursive lookups could cause stack overflow errors that would lead to a crashing app (DOS attack).
More info here: https://logging.apache.org/log4j/2.x/index.html

Upgrade log4j version to 2.17.0

---

riff-raff.yaml

This Pr sets the publicReadAcl in giants riffraff.yaml file now that this is a [required property](https://github.com/guardian/riff-raff/pull/665)

Specify publicReadAcl in riffraff.yaml

---

backend/app/extraction/email/eml/EmlParser.scala

make eml parser case insensitive with the multipart mimetypes and use the html block if there is no plain text

EmlParserImprovements

---

backend/app/commands/GetPages.scala

The hunt is over.
There was a stream which we were opening and, on a certain branch later on, not closing.
This was manifesting in prod as a totally different part of the application running out of streams which lead me on a wild goose chase into Akka HTTPs streaming result implementation - bit of a waste of time but I learnt a lot.
Honestly this entire bit of code could do with a rewrite, we get the preview from storage and then at the end decide to return `List.empty` if the metadata has no highlights. But for now I'll do this and we can restructure later.

Do close the streams

---

backend/app/AppComponents.scala
backend/app/controllers/frontend/App.scala
backend/conf/routes
build.sbt
scripts/teamcity.sh

Ronseal.
~We weren't including the public folder in the build.~
It looks like teamcity wasn't resolving the symlink correctly in the JDeb build - so manually `cp` it instead.

JDeb packaging symlink fix

---

backend/app/AppComponents.scala
backend/app/commands/GetPagePreview.scala
backend/app/commands/GetPages.scala
backend/app/controllers/api/PagesController.scala
backend/app/controllers/api/Resource.scala
backend/app/model/index/Page.scala
backend/app/services/index/ElasticsearchPages.scala
backend/app/services/index/Pages2.scala
backend/app/utils/PDFUtil.scala
backend/conf/routes
frontend/src/js/App.js
frontend/src/js/components/PageViewer/Page.module.css
frontend/src/js/components/PageViewer/Page.tsx
frontend/src/js/components/PageViewer/PageCache.ts
frontend/src/js/components/PageViewer/PageHighlight.tsx
frontend/src/js/components/PageViewer/PageOverlayText.tsx
frontend/src/js/components/PageViewer/PageViewer.module.css
frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/PdfHelpers.ts
frontend/src/js/components/PageViewer/VirtualScroll.module.css
frontend/src/js/components/PageViewer/VirtualScroll.tsx
frontend/src/js/components/PageViewer/model.ts
frontend/src/js/util/LruCache.ts

Just thought I'd open a PR now because this could get pretty long. This is not production ready but has approximate feature parity with the existing page viewer.
The main intention of this rework is to remove the synchronous nature of the old API in order to give us a well performing foundation for the page viewer MVP.
Rather than modify the existing code I've added new Typescript/Scala files. The older versions can be retired in the future if we decide this is a good approach.
You can access the new version of the page viewer by changing `/viewer/:uri` to `/viewer2/:uri` in this build.
I'll try to be very descriptive in this PR for future info but will happily run through after standup or whatever.
https://user-images.githubusercontent.com/5560113/156780098-b6732ee0-7e95-44e6-af71-ae8fdfb …

PageViewer: Mk. III Mod. A

---

frontend/src/js/components/SearchSidebar/SearchSidebar.js

Small quality of life change. 
I've noticed people tend to have a *lot* of workspaces and comparatively few datasets. This is usually caused by public workspaces which take up a lot of vertical screen real estate.
I just swapped them around to make it so datasets appear at the top, which for on going investigations is more useful.

move datasets to be above workspaces in sidebar

---

backend/app/extraction/email/msg/MsgEmailExtractor.scala
backend/app/model/Email.scala
build.sbt
riff-raff.yaml
scripts/teamcity.sh

This was originally part of work to get giant onto graviton. I'm not sure we'll achieve that but might as well make use of this work. This moves giant onto Java 11, with the various errors I encountered fixed by the age old method of 'google copy paste'
Upgrade to scala 2.12.6: https://stackoverflow.com/questions/50034684/simulacrum-macro-implementation-not-found
`.lines` now returns a stream https://stackoverflow.com/questions/68864659/problem-rewriting-scala-method-post-upgrade-to-scala-2-12-from-2-11 (I used a different solution to convert from the stream to a list)
This is currently live on playground https://playground.pfi.gutools.co.uk/workspaces/56b36105-498f-45a2-a7bb-ddf3a34c0c6c I've tested search and file upload
Newer better faster shinier onwards and upwards

Move giant to Java 11

---

backend/app/AppComponents.scala
backend/app/controllers/api/Authentication.scala
backend/app/services/MetricsService.scala
backend/app/utils/auth/providers/PanDomainUserProvider.scala
backend/test/utils/auth/providers/PanDomainUserProviderTest.scala

This PR adds Giant usage events to CloudWatch. We can then add Giant usage to our [Grafana dashboard](https://metrics.gutools.co.uk/d/BjGFOolnk/investigations-tools-usage?orgId=1&refresh=1d&from=now-7d&to=now).
As we won't be recording usage events when Giant is being run offline, we decided to send events to CloudWatch at the same time as PanDomain authentication validates a user, as this only happens online.
We have deployed to [Giant Playground](https://playground.pfi.gutools.co.uk) and events are being sent to CloudWatch.

Usage events in cloudwatch

---

riff-raff.yaml

Following from https://github.com/guardian/riff-raff/pull/692 - rex is the only stage on giant at the moment so let's tell riffraff that

Make rex the only allowed stage for giant deployment

---

backend/app/services/MetricsService.scala

This PR changes the CloudWatch usage metric from Username to UserEmail to be consistent with Lurch's usage metric.
Initially we intented to have Giant send the username to CloudWatch (without "@guardian.co.uk"), as Giant allows login with just username and password (no email address). We had planned to [change UserEmail to Username](https://github.com/guardian/lurch/pull/437) in Lurch for consistency. However, as we are only posting the usage metric on pandomain login for Giant, this only happens when we have an email address. Conseqnetly we no longer need to strip the "@guardian.co.uk" in Lurch to form a username and can simply use the UserEmail dimension in both Lurch and Giant.
Keeping the metric dimensions consistent will enable us to view the usage of individual users across both …

Make metric dimension consistent with Lurch

---

frontend/src/js/components/PageViewer/PageCache.ts
frontend/src/js/components/PageViewer/PdfHelpers.ts

If we don't pass a `worker` to `pdfjs.getDocument()`, pdf.js creates a new worker on every call:
https://github.com/mozilla/pdf.js/blob/5cf116a958548f6596674bf8d5ca0fe64aa2df3c/src/display/api.js#L331-L342
This causes a request to fetch `third-party/pdf.worker.min.js` and a new web worker thread per page loaded. When dragging across many pages, this thread leak crashes the browser when it hits about 30 or 40 threads.
Instead, we can create a worker (via pdf.js's wrapper) when we instantiate the page cache, and pass this in to `getDocument`

Use same worker thread for all pages

---

frontend/src/js/components/viewer/EmbeddedPdfViewer.tsx

This adds rotate clockwise/anticlockwise buttons to giant. It's pretty nasty dom manipulation, but is what's recommended in the pdfjs docs https://pdfjs.express/blog/how-to-build-pdf-viewer-jquery-pdfjs
The rotate buttons normally live in the secondary menu, which we hide in order to get rid of the download button. It might be worth changing our approach there and just hiding download rather than the entire right hand menu. I think even if we do that though it's a good idea to promote the rotate buttons to the main toolbar so they are easy to find.

Add rotate buttons to pdf viewer

---

frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/VirtualScroll.tsx

This fixes an issue whereby dragging the scrollbar causes huge numbers of requests for intervening pages. This slows down the loading of the page the user settles on, because of the large number of responses that need to be handled for the pages the user scrolled past.
The solution is to debounce the page number update, but only if there has been a discontinuity in the page numbers. This avoids compromising the experience of smooth scrolling.
Separately, I've also throttled the scroll events to avoid large numbers of calls to `getPages`. This doesn't appear to be an issue on my machine but on a slower one it could be.
https://user-images.githubusercontent.com/5122968/172441224-80984ae6-5ee8-4f40-9302-b468500c949a.mov
https://user-images.githubusercontent.com/5122968/172441269-2e5a9aff-fcb5 …

Prevent page request thrashing on scrollbar drag

---

frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/VirtualScroll.tsx

We set initial state values for `botPage`, `midPage`, `topPage`, but then we have a `useEffect()` which re-computes them from the viewport on init.
This causes it to unnecessarily unmount the third page on every load, which exposes an underlying problem with promise callbacks firing for pages after they've been unmounted.
The promise [cleanup problem](https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup) needs a separate solution (think we may need to wrap those promises into [cancellable promises](https://dev.to/praveenkumarrr/cancellable-promises-in-react-and-why-is-it-required-5ghf)) but this stops us pointlessly mounting then unmounting the third page on every fresh page load.

Do not setPagesToLoad twice on init

---

backend/app/controllers/api/PagesController.scala
backend/app/model/frontend/HighlightableText.scala
backend/app/model/index/Page.scala
backend/app/utils/PDFUtil.scala
frontend/src/js/components/PageViewer/Controls.tsx
frontend/src/js/components/PageViewer/FindInput.module.css
frontend/src/js/components/PageViewer/FindInput.tsx
frontend/src/js/components/PageViewer/Page.tsx
frontend/src/js/components/PageViewer/PageCache.ts
frontend/src/js/components/PageViewer/PageHighlight.module.css
frontend/src/js/components/PageViewer/PageHighlight.tsx
frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/VirtualScroll.tsx
frontend/src/js/components/PageViewer/model.ts
frontend/src/js/util/stringUtils.ts

Since our existing text view (as well as Google Docs) allows navigation between individual highlights, I thought it would be good to have it behave this way in the new page viewer.
The backend now gets the page hits (which is fast), and then for each page hit parses the highlights (which is slower).
So for searches with hits on lots of page, performance is noticeably slower. But more specific searches return quickly.
In Playground searching Functional Programming in Scala:
- "the" takes 10 seconds
- "function" takes 6 seconds
- "monoidal" takes 366 milliseconds
- Spinner while find is pending
- Do not quote the query when getting find hits, i.e. allow stemming by default and let the user put quotes if they don't want stemming. (Beforehand we were quoting when getting the page hits, but …

Navigate between individual highlights

---

backend/app/controllers/api/PagesController.scala
backend/conf/routes
frontend/src/js/components/PageViewer/Controls.tsx
frontend/src/js/components/PageViewer/FindInput.tsx
frontend/src/js/components/PageViewer/PageCache.ts
frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/VirtualScroll.tsx
frontend/src/js/util/LruCache.ts

There is a lot of state associated with highlights and navigating between them.
In order to not duplicate it all when I add "search in document" highlighting, I've moved as much as possible into `<Controls />` so that when I add the search controls I'll get a lot of functionality for free and properly encapsulated.
On refactor, the complex chain of state changes culminating in `triggerHighlightRefresh` was causing bugs, so I made the following changes:
- Remove `triggerHighlightRefresh` and refresh highlights when `findQuery` changes
- Group `pageCache.setFindQuery` and the subsequent re-rendering of pages together in the above effect to reduce chance that these end up out of sync
- Do not go to the server when `findQuery` is emptied, but rather wipe the highlights from cached pages. This …

Move highlight state to <Controls /> component

---

cli/src/main/scala/com/gu/pfi/cli/DeleteIngestions.scala
cli/src/main/scala/com/gu/pfi/cli/Main.scala
cli/src/main/scala/com/gu/pfi/cli/Options.scala
cli/src/main/scala/com/gu/pfi/cli/model/ConflictBehaviour.scala
cli/src/main/scala/com/gu/pfi/cli/service/CliIngestionService.scala

Prior to this PR, the delete-ingest CLI command only worked where the blobs in an ingestion didn't exist in any other ingestions, or you specified every single ingestion URI where the files included in an ingestion are included.
This was a problem as there are lots of files that are likely to exist all over the place, for example `.DS_Store` files created by macOS. 
This introduces a new `--conflictBehaviour` parameter allowing cli users to specify the behaviour in the scenario where a file exists in more than one ingestion. The options are:
- stop: the previous behaviour - throw an exception explaining what's gone wrong, including sharing the names of the other places the file exists
- skip: skip the file but carry on deleting everything else in the ingest
- delete: delete the file …

CLI delete ingestion improvements

---

frontend/package-lock.json
frontend/package.json
frontend/src/js/App.js
frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/PdfHelpers.ts
frontend/src/js/components/PageViewer/VirtualScroll.tsx
frontend/src/js/components/PageViewerOrFallback.tsx
frontend/src/js/components/viewer/DeleteButtonModal.tsx
frontend/src/js/components/viewer/DocumentMetadata.js
frontend/src/js/components/viewer/Viewer.tsx
frontend/src/js/components/viewer/ViewerActions.js
frontend/src/js/types/User.ts

This makes the new page viewer the default.
It will use the old viewer if the document has no pages (typically this means it was first uploaded before we had implemented the page extractor on the backend)
There is a "view as text" button which opens in a new tab:
- Do we still need a feature switch? Should this be a user-level, or should it allow us to unilaterally switch page viewer on/off if we discover issues?
- *Answer: just have an escape hatch button "view as text"*
- Do we care about comments? Or can we accept that the page viewer will disable commenting (and viewing comments) on docs with pages, until we implement comment logic for the page viewer? (See usage stats in [Trello](https://trello.com/c/wpIOExSS/2014-default-to-page-viewer-but-have-text-view-available-for-comments-and-no …

Wire up new page viewer

---

backend/app/controllers/api/PagesController.scala
backend/app/services/index/Pages2.scala

The format of the id used for pages in ES and S3 changed in https://github.com/guardian/pfi/pull/884 and https://github.com/guardian/pfi/pull/886 to be
```
{documentHash}-{pageNumber}
```
We use the `pageCount` endpoint to determine whether to use the page viewer or fall back to the old text/OCR/preview viewer. This means that documents with the old id would have a non-zero page count, but fetching the page preview or data by id would fail because of the different id format.
This PR changes the `pageCount` endpoint to return 0 pages for documents with the old id, which will tell the frontend to fall back to the old viewer.
Examples of old-style and new-style ES pages docs:
```json
{
"_index": "pfi-pages-text",
"_type": "_doc",
"_id": "_z1TYXIBKUVvS4VMPvmz",
"_version": 1,
"_score": 0, …
```

Only count pages with 'new' id type when returning pageviewer page count

---

backend/app/utils/HtmlToPlainText.scala
build.sbt

[Snyk](https://app.snyk.io/org/guardian-investigations/project/a40df7ee-382f-42d9-b182-53f7f515cca4) has identified a vulnerability with Tika which can also bee seen on [maven central](https://mvnrepository.com/artifact/org.apache.tika/tika-parsers).
This bumps tika to the next version without the vulnerability. There's a comment in the code:
```
// NOTE: When you update tika you need to check if there are any updates required to be made to the
// conf/org/apache/tika/mimecustom-mimetypes.xml file
```
Here are the release notes for [1.2.1](https://tika.apache.org/1.21/index.html) and [1.2.2](https://tika.apache.org/1.22/index.html) - as far as I can tell there are no updates needed to this file 
Deploy to playground and try an ingest. Something for after easter!

Bump tika to 1.22 to remove vulnerability

---

backend/app/AppComponents.scala
build.sbt

In the past we've had Giant incidents caused by exhaustion of the S3 connection pool.
We've tried to mitigate by closing input streams (https://github.com/guardian/pfi/pull/924, #11) but they still crop up sometimes during large ingestions when the workers have lots of connections to S3.
The new page viewer (#32) has made this more common because it also makes lots of requests to S3 for individual pages.
We want to get visibility on when we're in danger of hitting this issue. AWS provides extra metrics from its Java SDK, including around connection pools to AWS services such as S3, but you need to do some special stuff to enable it.
You can apparently do it by calling some methods on `AwsSdkMetrics`:
https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/ …

Send AWS SDK metrics to CloudWatch

---

README.md
backend/app/services/Config.scala
backend/app/services/previewing/HtmlPreviewGenerator.scala
backend/app/services/previewing/PreviewService.scala
backend/conf/application.conf
frontend/src/js/components/viewer/EmbeddedPdfViewer.tsx
scripts/cluster-setup.sh

Email preview is currently broken. This is due to some linux permissions issue when giant tries to call out to chromium-browser to generate the PDF preview. 
It would definitely be possible to fix the permissions issue (giant would need write access to /home/pfi/snap I think) but @itsibitzi suggested abandoning chromium-browser and instead using wkthmltopdf.
This works round the permissions issue, and should somewhat speed up the preview process now that we're not spinning up an entire browser to generate the pdf.
Separately, I noticed that we're not properly url encoding the filename in the url we pass to PDF.js - this PR also fixes that. 
Open any .eml file in giant - here's an example on playground https://playground.pfi.gutools.co.uk/viewer/CAGHe3Pmc37CiMwbWks-CVOiM=uYhnpvq2=Zg51dkESL8 …

Fix email preview, use wkhtmltopdf for html to pdf conversion

---

Brewfile
Brewfile.lock.json
docker-compose.yml
scripts/start-backend.sh

The current docker image we're using for neo4j doesn't support M1 arm64 macbooks. Neo4j don't support version 3.5 of neo4j anymore so aren't providing images but there is an experimental one we can use that seems to work: https://hub.docker.com/r/neo4j/neo4j-arm64-experimental/tags?page=1&name=3.
Elasticsearch also fails to start on a M1. @joelochlann  found that [this](https://stackoverflow.com/questions/50314586/elasticsearch-fails-to-start-config-seccomp-and-config-seccomp-filter-are-neede) solution worked - setting `bootstrap.system_call_filter=false` 
Note that people using M1 chips will need to either use the start-backend script or set `export NEO4J_IMAGE_OVERRIDE=neo4j/neo4j-arm64-experimental:3.5.30` prior to running docker compose in order to set docker to user the experimental …

Support local development on ARM64 laptops

---

backend/app/utils/Ocr.scala

In guardian/giant#14 we changed `--redo-ocr` => `--skip-text`
Part of the justification was [this issue](https://github.com/ocrmypdf/OCRmyPDF/issues/700) which was fixed in [version 11.4.4](https://ocrmypdf.readthedocs.io/en/latest/release_notes.html#v11-4-4).
I'm currently upgrading our Amigo bake to use [13.7.0](https://ocrmypdf.readthedocs.io/en/latest/release_notes.html#v13-7-0) so this should no longer be a problem.
So I'm switching back to `--redo-ocr`.
In short, `--redo-ocr` does more work (therefore is probably slower, though we haven't benchmarked) but it will try and add extra OCR text even to pages that already contain printable text. For instance, in a normal text PDF that contains images which happen to have text in them, it will get the text in those images. `--skip-text` …

--redo-ocr not --skip-text

---

package-lock.json

This file is breaking Giant's snyk integration as it then goes looking for a package.json file that doesn't exist

Remove empty package-lock.json

---

backend/app/controllers/api/Blobs.scala
backend/app/services/index/ElasticsearchResources.scala
backend/app/services/index/Index.scala

Make the ingestion param optional so you can get all blobs under a collection without also specifying an ingestion.
This is so the CLI can have a "delete by collection" functionality. Every use case we've had for deletion via the CLI involves deleting an entire collection and it's annoying to have to find out all the ingestions first and pass them as an array to the CLI.
This could also form the basis of a (very dangerous! probably admin-only) "delete collection" button in the UI, if we wanted it.

getBlobs by collection

---

backend/app/commands/DeleteResource.scala
backend/app/controllers/api/Blobs.scala
backend/app/services/manifest/Manifest.scala
backend/app/services/manifest/Neo4jManifest.scala
backend/conf/routes
cli/src/main/scala/com/gu/pfi/cli/service/CliIngestionService.scala
frontend/src/js/services/BlobApi.ts

I can't think of a case where we delete a blob - either from UI, or as part of collection/ingestion deletion - where we don't want to remove any workspace references to it and remove the dangling file parent.
You could argue it's slightly more efficient not to remove the file parent when later on you're going to wipe the whole ingestion, but I don't think this is worth the complication. You definitely want to remove the workspace references.

Remove deleteFolders param

---

backend/app/controllers/api/Collections.scala
backend/app/services/manifest/Manifest.scala
backend/app/services/manifest/Neo4jManifest.scala
backend/conf/routes

The deletion functionality I'm adding to https://github.com/guardian/giant-utils deletes by collection, not ingestion (since that's always what we've done in practice).
For that to work, I need a "delete collection" endpoint to call once all the blobs have been deleted.

Delete collection endpoint

---

build.sbt
common/src/main/scala/services/FingerprintServices.scala

I've been playing around learning and implementing [Webauthn](https://webauthn.guide) (Yubikeys etc). WIP branch here: [mbarton/giant/webauthn](https://github.com/mbarton/giant/tree/mbarton/webauthn).
To use [webauthn4j](https://webauthn4j.github.io) I had to update to Jackson 2.13 and the latest Play 2.8. As part of this I was going through all the libraries and noticed that we don't really need Guava in common since we're just using it to hash files.
We do need it in the CLI to walk the file tree so I've just moved the dependency there. The CLI doesn't depend on the Play Framework at all (just play-json) so it doesn't matter what version of Guava we use. I haven't upgraded it though just to keep the changes minimal.
One less thing to worry about for the next Play upgrade :)

Remove Guava from common

---

backend/app/services/manifest/Neo4jManifest.scala

Since [deletion was introduced](https://github.com/guardian/pfi/pull/441), we've never been cleaning up the neo4j structures underneath blobs. (This is relevant only for blobs with children, i.e. files containing other files such as zips, archives, mailboxes, etc.).
When we delete the ingestion at the end of the process, we delete all resources whose URI starts with the ingestion name:
https://github.com/guardian/giant/blob/512006051e4fc1e0fca4c545bf61713fd59fa3df/backend/app/services/manifest/Neo4jManifest.scala#L1017-L1036
However, URIs start again when there is an intervening blob, e.g.
1. collection
2. collection/ingestion
3. collection/ingestion/directory
4. collection/ingestion/directory/zipfile
5. zipfile/directory
6. zipfile/directory/file
(See [The Giant File …

Delete blob descendants from neo4j when deleting the blob

---

backend/app/controllers/api/Blobs.scala
backend/app/services/index/ElasticsearchResources.scala
backend/app/services/index/HitReaders.scala
backend/app/services/index/Index.scala
backend/conf/routes
cli/src/main/scala/com/gu/pfi/cli/DeleteIngestions.scala
common/src/main/scala/model/index/IndexedBlob.scala

When fetching blobs, you can now pass `inMultiple=true` to get only blobs that are also in other collections/ingestions than those supplied.
This is useful to do before deleting a collection, so you can check that blobs also exist in other collections are safe to delete.
```url
?collection=c&inMultiple=true
```
returns blobs in collection c and at least one other collection
```url
?collection=c&ingestion=i&inMultiple=true
```
returns blobs in ingestion c/i and at least one other ingestion
Because they're arrays
Because it's in elasticsearch anyway and it's useful not to have to compute this from the ingestions when consuming the API.
```json
{
"blobs": [
{
"uri": "MVGTRpihjQaCY3Rfn3RJIuXOwseGAPVo3ITre4Svc_oArVwofwBya0cGIJqYF8sdFOzP30Lb3u_4nS-qqVH6cQ",
"collections": [
"joe Documents"
], …
```

`inMultiple` flag to get only those blobs that are in multiple collections

---

backend/app/controllers/api/Blobs.scala
backend/app/services/index/ElasticsearchResources.scala
backend/app/services/index/Index.scala
backend/conf/routes

Currently the `getBlobs` endpoint can only return up to 500 blobs due to limitations of the elasticsearch search API. We could page through to get more, though it's not really suitable for returning hundreds of thousands of results (there is an inbuilt limit of [10,000](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/paginate-search-results.html))
For that reason, it would be useful to have an endpoint for counting the number of blobs, so we can tell the user at the start of a deletion how much work there is to do, and track progress through it.

Add count blobs endpoint

---

riff-raff.yaml

Following the request from DevX (see email 'riff-raff.yaml and bucket names') to stop hard coding the names of our infrastructure buckets (this is also in line with [guardian recommendations](https://github.com/guardian/recommendations/blob/main/github.md#repository-contents)), this pulls the various giant ones into SSM. I've already created all the relevant parameter store parameters.
Note that this doesn't add much benefit for us because we've got two aws-s3 deploy steps which are still hard coding the bucket. I'm going to ask DevX to support SSM lookup for `aws-s3` deploys as well

In riff-raff.yaml, use ssm for artifact buckets

---

backend/app/commands/DeleteResource.scala
backend/app/services/ObjectStorage.scala
backend/test/extraction/WorkerTest.scala
backend/test/test/TestObjectStorage.scala

After an excellent pairing session with @rtyley, we realised that we could get some performance gains by sending multiple keys to delete in a single S3 call, rather than making multiple calls.
This means we make at most two delete requests to S3: one to delete everything from the preview bucket (page previews and the whole-document preview), and one the delete the blob from the ingest bucket.
The biggest gains would be in documents with many pages since before we were making at least one call per page, e.g. 324 requests become 2 requests.
But even for a document with one page, we still reduce the S3 requests from 3 to 2.
**900ms**
```
Delete page previews: took 0 minutes 0 seconds 780 milliseconds
Preview S3 delete: took 0 minutes 0 seconds 5 milliseconds
Ingest S3 delete: took 0 minutes …
```

Batch S3 deletion requests

---

build.sbt

Snyk is reporting two critical vulnerabilities in Giant related to tika-parser - see https://app.snyk.io/org/guardian-investigations/project/a40df7ee-382f-42d9-b182-53f7f515cca4
I'm not certain that this will resolve them but it's the highest version of tika-parser we can move to without hitting a jackson-databind dependency clash as later versions of apache-tika increase the version of the jackson-core library above 2.12.0 - which clashes with other dependencies (I didn't look into this too deeply - the error was `An exception or error caused a run to abort: Scala module 2.11.2 requires Jackson Databind version >= 2.11.0 and < 2.12.0 ` and you can see that version [1.26](https://mvnrepository.com/artifact/org.apache.tika/tika-parsers/1.26) of tika-parsers introduces a version about …

Bump tika-parsers to 1.25 in an attempt to fix snyk vulnerability

---

backend/app/extraction/email/mbox/MBoxEmailDetector.scala

Changes the way we check the number of messages in a mailbox.
Using  `getMessages` specifying a start and end index occasionally throws exceptions.
Using `getMessageCount` is a more specific way of determining the number of messages in the mailbox.

Count Mailbox messages

---

build.sbt

During a recent ingest we noticed giant workers failing with the error `Uncaught error from thread [pfi-work-context-28]: org/bouncycastle/asn1/bsi/BSIObjectIdentifiers, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[pfi]` - with the specific error being `java.lang.NoClassDefFoundError: org/bouncycastle/asn1/bsi/BSIObjectIdentifiers`
My initial attempt to fix this was to just bump the version of bouncycastle up to the latest (1.70) as I'd spotted in the dependency tree that older versions of the  bouncycastle library were being evicted by version 1.69. This didn't solve the problem, but I've left in the change.
What I think the actual issue was is that the class in question - BSIObjectIdentifiers - has been pulled out into a [separate bcutil …

Add explicit bouncycastle util library dependency

---

riff-raff.yaml

Following from https://github.com/guardian/investigations-platform/pull/436 this is the change to tell Giant to use an ARM64 AMI baked in amigo (https://amigo.gutools.co.uk/recipes/investigations-elasticsearch-7-arm64) for elasticsearch

Move elasticsearch onto arm64 AMI

---

frontend/package-lock.json
frontend/src/js/components/PageViewer/VirtualScroll.tsx

For a one-page doc, it would attempt to load pages 2 and 3:
It fails, causing cascading errors in pdf.js:
And, for some reason, when running locally this results in a massive iframe covering the page and making it unusable:
In prod, it stills spews errors because of trying to fetch pages 2 and 3 which don't exist, but for some reason the iframe doesn't appear.
It loads just one page, and there's no iframe:

Do not fetch pages outside the total length of the doc

---

frontend/package-lock.json
frontend/package.json
frontend/src/js/util/auth/authFetch.ts
frontend/src/js/util/store.js

Upgrades `redux` from version 3.7.2 to 4.2.1, fixing [a vulnerability](https://app.snyk.io/org/guardian-investigations/project/5b846eac-6418-4ca9-ae1b-f1cded91cfd6#issue-SNYK-JS-LODASHES-2434283).
Run Giant locally and do a search

Upgrade redux 3.7.2 -> 4.2.1

---

backend/app/utils/HtmlToPlainText.scala
build.sbt

This resolves https://app.snyk.io/vuln/SNYK-JAVA-ORGJSOUP-1567345 with a minor version bump of jsoup. 
Tested on playground

Bump jsoup to version 1.14.2 to fix vulnerability

---

cli/src/main/scala/com/gu/pfi/cli/ingestion/CliFileWalker.scala

In order to fix the scala cli, this somewhat reverts some of the changes made in https://github.com/guardian/giant/pull/75/files#diff-458af680964b84c1a157d7485ffa9b0a5a4ab961148a632b3fb6c3507f65db3c 
In Scala 2.13, Streams went away, replaced by LazyLists. The file linked to above shows the changes implemented by @mbarton in his heroic scala 2.13 upgrade. Unfortunately this had the effect of breaking the scala cli - it runs succesfully but doesn't detect any of the files in the directory being ingested.
This change fixes that issue, by just using a conventional `List` to store the big list of files. I'm not much of an expert on scala streams/lazy lists/iterators etc. I _think_  that since we were already deliberately eagerly evaluating the file list this change won't have an enormous …

Fix scala cli - use list instead of lazylist

---

.tool-versions
frontend/src/js/components/PageViewer/Controls.tsx
frontend/src/js/components/PageViewer/Page.tsx
frontend/src/js/components/PageViewer/PageCache.ts
frontend/src/js/components/PageViewer/PageViewer.tsx
frontend/src/js/components/PageViewer/PdfHelpers.ts
frontend/src/js/components/PageViewer/VirtualScroll.module.css
frontend/src/js/components/PageViewer/VirtualScroll.tsx
frontend/src/js/components/PageViewer/model.ts
frontend/src/js/util/LruCache.ts

This PR is a collaboration with @philmcmahon and @joelochlann 
This PR updates the pdf viewer with zoom-in/zoom-out functionality. It adds a `scale` state to the `PageViewer` which is used to control the container size and as a result controls how big or small the page should be rendered.
A new function `refreshPreview` is added in the  in PageCache class, that is responsible to update the existing preview in cache by rendering a new page and replacing the current preview in cache with the new preview. This way we avoid calling the server to retrieve preview for the page number.
In PdfHelpers, a new function `updatePreview` is implemented and when given the preview and a container size it renders a new page for that container size.
In the Page component, the `pageHeight` added to the …

Zoom in and zoom out pdf 

---

backend/app/controllers/api/Collections.scala
frontend/src/js/util/auth/authUploadWithProgress.ts

This PR adds a retry (up to 3 retries) on file upload requests if they fail for any reason.  
There's a delay (gap) between the failure time and the retry. This delay starts at 1 second * random number between 0-1, and it increases on every retry. This increase is called **exponential backoff** which is a recommended strategy on retry mechanism because the more retries that fail, there's bigger chance that we're dealing with an outage that could take time, so we don't want to put too keep calling the server if it's experiencing an outage that could last longer. 
There's also a randomness added to the backoff time in order to ensure that in the time of outage, if several clients are calling the server and encountering the error at the same time, they won't all re-send the request the …

Adding retry in client for upload failures

---

backend/app/services/observability/Models.scala
backend/app/services/observability/PostgresClient.scala
frontend/src/js/components/IngestionEvents/IngestionEvents.tsx

There is currently a bug the observability dashboard where if a file has been hashed but no extractor events have started then the whole dashboard crashes. This resolves that by adding a few ternaries.
At the same time I discovered an issue where fileSize isn't defined - currently in our postgres query there is no default, it can just be NULL. So I made it optional.
This PR also adds a 'key' property to all our lists/repeated divs to avoid the [unique key prop warning](https://sentry.io/answers/unique-key-prop/).
At the same time I fixed our itemId in the EUI table to include the ingest ID (no user facing benefit here, just seems more accurate).
There's also silly pedantic change to rename metaData to metadata.
Tested on playground, it appears to fix the main bug described above.
Fewer …

Fix observability dashboard when no extractor events

---

frontend/src/js/components/IngestionEvents/AllIngestionEvents.tsx
frontend/src/js/components/IngestionEvents/IngestionEvents.tsx
frontend/src/js/components/IngestionEvents/MyUploads.tsx
frontend/src/js/components/IngestionEvents/types.ts

This PR adds a filter button group with 2 option of `all` & `errors only` in order to provide ability for filtering the ingestion events. 
This change is applied for both `My uploads` & `All ingestion events` views.

Add filter on dashboard for showing all or only errors 

---

frontend/src/js/actions/ingestEvents/updateCurrentWorkspace.ts
frontend/src/js/components/IngestionEvents/AllIngestionEvents.tsx
frontend/src/js/components/IngestionEvents/MyUploads.tsx
frontend/src/js/components/IngestionEvents/updateCurrentCollection.ts
frontend/src/js/components/IngestionEvents/updateCurrentIngestion.ts
frontend/src/js/reducers/urlParamsReducer.ts
frontend/src/js/types/redux/GiantActions.ts
frontend/src/js/types/redux/GiantState.ts

Stores the current workspace in the url of the 'My uploads' observability dashboard and current collection and ingestion in the url of the 'All ingestion events' dashboard. These values are used to set the initial values of their respective dropdowns on the dashboard pages.
- after refreshing the page, the user won't lose the ingestion events they were searching for
- the ingestion events from a specific ingestion can be sent between developers or from a user to a developer

Store current workspace, collection, and ingestion in URL of observability dashboards

---

backend/app/extraction/Worker.scala
backend/app/services/observability/Models.scala
backend/app/services/observability/PostgresClient.scala
frontend/src/js/components/IngestionEvents/IngestionEvents.module.css
frontend/src/js/components/IngestionEvents/IngestionEvents.tsx
frontend/src/js/components/IngestionEvents/types.ts

This PR adds a (hopefully) useful dropdown to rows on the ingestion events dashboard. The main aim is to show errors that have occurred during an ingestion together with the stack trace for debugging. I've also moved the 'path' field into this expanded row to save some space, and added some text (not so sure how useful this is) giving some info about the file.
This also adds a new 'ingest run time' column and 'status' column indicating whether the ingest has finished or not. 
It looks like this:
You can just click on any row and see what it looks like! Tested on playground

Add a dropdown to ingestion events dashboard rows, showing errors and other data. 

---

backend/conf/application.conf
frontend/src/js/components/Uploads/FileList.tsx
frontend/src/js/components/Uploads/UploadFiles.tsx

In https://github.com/guardian/pfi/pull/839 we set the file upload limit to 100MB. This PR bumps that further. As  far as I can tell, there was no particular reason to limit workspace uploads to 100MB. We have had at least one user need to upload a file larger than 100MB, this change would have helped them. 
As a follow up piece of work, we should expose the file size limit in the UI and warn users when they try to upload a file above the limit.
Tested on playground with a 190MB file
There could be performance implications of allowing such a large file to be uploaded via the UI. Hopefully the new dashboards should allow us to pick those up as and when they occur

Increase max size limit to 250MB

---

frontend/src/js/components/Settings/SettingsSidebar.js

As we now have 2 new upload related dashboards called 'my uploads' and 'all ingestion events' this one needs a more accurate name

Rename 'uploads' settings option to 'uploads calendar'

---

backend/app/services/observability/Models.scala
backend/app/services/observability/PostgresClient.scala
frontend/src/js/components/IngestionEvents/IngestionEvents.tsx

We have a bug at the moment where if there is no `path` available for a `BlobStatus` then the dashboard will crash. This PR fixes the problem at both ends - filtering out null paths both on the server and the client.
Tested locally, think this is simple enough to go out as is!

Clean paths property of ingestion events in parser

---

frontend/src/js/components/IngestionEvents/IngestionEvents.tsx

Adds pagination to ingestion events tables on "My uploads" and "All ingestion events" pages
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Add pagination to ingestion events table

---

backend/app/services/observability/PostgresClient.scala

We've found a few cases of bugs where ingestion fails only to be retried minutes later, forever. These retries create thousands of rows in `ingestion_events` which makes the observability dashboard query timeout. This PR should fix the dashboard for ingests with problem files in an infinite retry cycle while we come up with a better retrying solution.
In a follow-up we plan to put blob ids which have more than 100 ingest events back into the dashboard table, with a helpful explanation as to what's going on.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour …

fix: Exclude infinitely-ingesting blobs from observability query

---

backend/app/controllers/api/IngestionEvents.scala
backend/app/services/observability/Models.scala

In future we hope that if we see an alarm or user error report with giant, we will be able to use the observability dashboard to help diagnose the issue. With the current implementation, it is only possible to view the observability data associated with an upload if the 'viewing' user has the rights to see the relevant collection. This PR changes the behaviour so that admin giant users are able to 'spy' on the observability data associated with any users' collections. 
Security wise, this doesn't represent a significant change as Giant Admins are already able to add themselves to any collection. We'd prefer they didn't do this though as it allows them to access all the files a user has uploaded.
The new logic is:
- If you have view access to a collection, you can see all observability …

Allow admins to view all observability data

---

backend/app/controllers/api/Blobs.scala
backend/app/controllers/api/Workspaces.scala
backend/app/model/manifest/Collection.scala
backend/app/services/manifest/Manifest.scala
backend/app/services/manifest/Neo4jManifest.scala
backend/app/utils/controller/FailureToResultMapper.scala
backend/conf/routes
backend/test/controllers/api/WorkspaceSharingITest.scala
common/src/main/scala/utils/attempt/Failure.scala
frontend/src/js/components/viewer/DeleteButtonModal.tsx
frontend/src/js/components/viewer/ViewerActions.js
frontend/src/js/services/BlobApi.ts

This PR adds delete functionality for all users within document viewer. However, the delete may only pass if 
- the file doesn't have children and
- the file is within only 1 collection and the user has view access on the file
- Or the file is within several collections that have been created by the requesting user
This was tested both locally and in playground

Add delete functionality in document viewer for non-admin users

---

package-lock.json

All npm stuff lives in the frontend subdirectory, so we don't need a package-lock at the root. Also, having one here confuses the snyk GHA runner

Remove redundant package-lock.json

---

build.sbt

See https://app.snyk.io/org/guardian-investigations/project/a40df7ee-382f-42d9-b182-53f7f515cca4#issue-SNYK-JAVA-ORGPOSTGRESQL-2970521 - this resolves https://cwe.mitre.org/data/definitions/89.html
This is a patch version bump so should be very safe

Bump postgresql library to 42.2.27 to fix vulnerability

---

backend/app/extraction/ocr/OcrMyPdfImageExtractor.scala

This PR removes alpha channel from tiff files since ocrMyPdf can not process image files with alpha channel enabled. 
tested locally

remove alpha channel from tiff file

---

backend/app/extraction/ocr/OcrMyPdfExtractor.scala
backend/app/utils/Ocr.scala

ocrMyPdf fails to process files that contain images with over 500000000 pixels. Although this default max limit can be increased in ocrMyPdf using `max-image-mpixels` param, the tesseract would still fail complaining about the image pixle with this error `Error in pixCreateHeader: requested bytes >= 2^31`
This PR is adding a pre-process call which reduces the pdf image ppi to 300 using ghostscript. If the images are originally below 300, they would stay with their original ppi. 
This not only fixes the ocrMyPdf failure, but also improves the performance of ocrMyPdf greatly for any file with an image ppi over 300. 
**Note:** If the pre-process call fails for any reason, it would not break the rest of the process. `Option` is used as the return type so that it would return the down sampled …

reduce pdf image ppi before running ocrMyPdf

---

postgres/cdk/lib/giant.ts

There is currently a mismatch between the version of postgres we are running locally via docker and the version we are running in RDS. Rather than downgrade our local version I decided to upgrade to 15.3 in RDS. As we're using 15.3 locally already, we have a good amount of confidence that we won't have any compatability issues.
This has already been deployed on CODE and doesn't appear to cause any issues. 
Deploy steps for PROD:
- merge this
- deploy via riffraff 
Queries that work locally should also work in AWS 🎉

Bump postgres to version 15

---

backend/app/AppComponents.scala
backend/app/controllers/api/Ingestion.scala
backend/app/ingestion/phase2/IngestStorePolling.scala
backend/app/services/Config.scala
backend/app/services/IngestStorage.scala
backend/app/utils/AwsDiscovery.scala
backend/conf/application.conf
backend/conf/routes
backend/test/test/integration/Helpers.scala

We have seen an issue in giant where if a file fails the initial ('phase 1') ingestion step - i.e. any of the below processes fail:
- hashing
- copying to data bucket with hash as the key
- mimetype detection with tikka
- determining what extractors need running based off the mimetype
- writing manifest to neo4j
- writing to elasticsearch
....then the file will remain in the ingest bucket and be retried over and over again. This adds a lot of noise to the logs and observability dashboard and may result in increased AWS spend as workers try over and over again to ingest the same files.
This PR prevents this behaviour by removing ingest files from the ingest bucket and copying them to a 'dead letter' bucket. In order to get giant to have another go at ingesting those files, they will have …

When a file fails to ingest, move to a 'dead letter' bucket

---

frontend/src/js/components/IngestionEvents/IngestionEvents.tsx

At the moment we only show the 'error' icon in the dashboard if an extractor has failed. There are other error conditions, such as if a file fails to be added to neo4j/elasticsearch. In the latter case (fail to add to elasticsearch, e.g. if elastic is down) then the file _may_ still have succesful extractor runs, but have problems associated with it.
We are already exposing all errors that are written to postgres on the client side UI at the bottom of the 'expanded row' view. This PR makes them a bit more discoverable by changing the status icon for the row to 'complete with errors' (warning icon)
I've tested this locally, I think it's a small enough change not to test on playground (as this would be a bit challenging to reproduce such an error condition). Happy to try test it if others …

Show error icon in events dashboard for non-extractor errors

---

backend/app/extraction/tables/ExcelTableExtractor.scala

This PR fixes a bug where an excel date field has an invalid date value,, and therefore can not be converted to a Java date. `DateUtil.getJavaDate(dateAsDouble)` returns null if the provided argument is not a valid date. So the ingestion of the file was failing due to calling `toString` on a null and was getting a `NullPointerException` exception. 
Tested locally and in playground

Fix excel extractor failure on invalid dates

---

backend/app/extraction/Worker.scala
backend/app/services/manifest/Neo4jManifest.scala

When worker calls fetchWork, the resources that have `TODO` relationships will be returned so the worker can execute the relevant extractors. As part of the fetchWork, the `attempts` property of the TODO relationship is supposed to get updated. For a strange reason that I didn't fully understand, the query was not updating the TODO attempts. Therefore, everytime the worker is triggered, the task that has already been attempted is returned by the query meaning it's stuck in an infinite loop. 
The fix in this PR does the 2 followings:
- Fix the query so that the todo attempts is updated 
- Add a `Extraction_Failure` relationship between the relevant resource and the extractor, so that it is known to us that this extractor is not supported. This way the UI also shows that the extractor for …

fix bug where todo attempt was not updated after fetchWork

---

backend/app/services/observability/Models.scala
backend/app/services/observability/PostgresClient.scala
frontend/src/js/components/IngestionEvents/IngestionEvents.tsx
frontend/src/js/components/IngestionEvents/types.ts

Some file types fail to be ingested and ingestion is retried over and over in an infinite loop, inserting new rows into the observability database every few minutes. in #149 we stopped this from happening by moving failed files to a dead-letter bucket. 
Any files that have previously been in an infinite loop, and any files that cause this failure mode for other reasons that we haven't thought of in the future should be shown in the observability dashboard.
- files with more than 100 ingestion events are assumed to be stuck in an infinitely loop and, in order to improve performance, are excluded from the query that selects the data for the dashboard.
- These problematic files are added back into the observability dashboard. In order to avoid slowing down the query, we don't array aggregate …

Show infinitely looping files in observability dashboard

---

backend/app/extraction/tables/ExcelTableExtractor.scala

There was a file which had syntax error in one of the date fields that was using a formula. So the ElementText was returning a string that couldn't get converted to `Double`. I replaced the `toDouble` by `toDoubleOption` to avoid exception and extraction failure. 
e.g. the formula in the field can’t evaluate the value of a date field
Tested locally & in playground

fix invalid number error in excel extration

---

backend/app/services/manifest/Neo4jManifest.scala

Co-authored-by: Marjan Kalanaki <marjan.kalanaki@guardian.co.uk>
- At the moment, workers can get into a state where all three have a lock on the same blob. 
- This PR reverts some of the changes in #157 which we think introduced the bug that allows this invalid state.

Fix worker lock

---

backend/app/extraction/ocr/BaseOcrExtractor.scala
backend/app/extraction/ocr/OcrMyPdfExtractor.scala
backend/app/extraction/ocr/OcrMyPdfImageExtractor.scala
backend/app/utils/Ocr.scala
backend/app/utils/controller/FailureToResultMapper.scala
common/src/main/scala/utils/attempt/Failure.scala

This PR is adding a timeout to `ocrMyPdf` process. This is because there's been occurrences where ocrMyPdf gets stuck in processing a file and doesn't return any exit code. As a result, the worker waits forever until the file processing is completed or errored. 
The timeout duration is chosen based on the number of pages within a file and is giving at most 1 minute for every page plus an overall 5 minutes to mitigate the risk of un-necessary timeout for files with low number of pages, e.g. for a pdf page with 10 pages, 15 (10 + 5) minutes is allocated for timeout. 
Thanks to @zekehuntergreen who helped with looking through the ingestion_events table to confirm that (1 minute * numberOfPages) + 5 minutes should be more than enough time to allocate for the timeout duration of ocrMyPdf. …

add timeout to ocrMyPdf process

---

backend/app/extraction/email/eml/EmlParser.scala

`MimeBodyPart.getEncoding` can return null if the header is unavailable, leading to a null pointer exception when we call toLowerCase on the return value. Wrap the return value in an Option to handle this case.

Fix `NullPointerException` in `EmlEmailExtractor`

---

.github/workflows/build.yml

Following advice from @adamnfish and in an attempt to speed up giant builds (and generally be less wasteful), let's enable caching for the relevant [setup npm](https://github.com/actions/setup-node/tree/main) and [setup java](https://github.com/actions/setup-java#caching-sbt-dependencies) steps. 
We can also look at caching the docker containers we use to run the tests but I'm guessing that might be slightly more complex, so possibly for a future PR.
If this build completes https://github.com/guardian/giant/actions/runs/6614917759/job/17965921924 that will be encouraging. We'd then need to run a few more builds to get some updated build time data. 
Faster builds, less energy wastage, happy days

Enable caching for github actions workflow

---

frontend/package-lock.json
frontend/package.json

`react-scripts` has a dependency of `babel/traverse@7.21.5` which has a critical vulnerability.
However as it's used as a build tool as part of CRA we shall move it to `devDependencies`. 
See https://github.com/facebook/create-react-app/issues/11174
tested on CODE, and this should remove the critical vulnerability warning from Snyk once merged as Synk doesn't look at `devDependencies`.

Moving react-scripts to devDependencies as it's only used in build

---

frontend/src/js/components/viewer/PreviewSwitcher.js
frontend/src/js/util/resourceUtils.ts

This PR adds a check if resource has transcript, and returns the transcript.<language> for view query parameter. 
It also removes the `Text` tab on the viewer if resource has transcript.

Add transcript.<language> query param on transcribed resource url

---

frontend/src/js/components/viewer/PreviewSwitcher.js

This PR fixes the title of the language tab on viewer for the OCRed resources.
| Before      | After      |
| ----------- | ---------- |
| ![image](https://github.com/guardian/giant/assets/15894063/a34eca6f-26df-4f36-b404-62052b178230) | ![image](https://github.com/guardian/giant/assets/15894063/7374ae2e-0bb9-4a78-b3a2-84f834ba3aa9) |

Show correct title on viewer languange tab

---

backend/app/AppComponents.scala
backend/app/extraction/TranscriptionExtractor.scala
backend/app/services/index/HitReaders.scala
backend/app/utils/Whisper.scala
frontend/src/js/components/viewer/PreviewSwitcher.js
frontend/src/js/util/resourceUtils.ts

The main complex thing this PR does is in HitReaders (backend/app/services/index/HitReaders.scala) - modifying the transcription hit reader so that it doesn't discard the transcript text for languages which don't have highlights in them. It also fixes a bug where we I wasn't actually saving the translated transcript to elasticsearch (https://github.com/guardian/giant/compare/pm-transcription...transcription-tidy?expand=1#diff-c1413c4436e0eaed3ad9d530cfc47fc20c0831a5fa7ac8523690ec0d208ab182R60)
Also - remove various unused variables/comments and pull out the code to read the output transcript file into a separate function
Tested locally, everything was very broken before so I think this is a big improvement!

Fix transcription languages

---

backend/app/utils/RequestLoggingFilter.scala
backend/app/utils/auth/AuthActionBuilder.scala

This removes request logging for succesful requests to '/healthcheck' from giant logs, which makes up a lot of the noise. 
It also removes 'authentication succeeded' logging, I think it's ok to only log in the 'failure' path. 
Tested locally.
##success?
More readable logs, less filtering required

Make giant logging less noisy

---

frontend/src/js/util/resourceUtils.ts

This PR temporarily increases the `MAX_NUMBER_OF_CHILDREN` from 1000 to 1100. This is because there seems to be a bug in UI to display the children of a folder when it's over 1000 files. A ticket was created to fix this bug but we are temporarily increasing the limit as a quick fix.

Temprarily increase the max number of children

---

backend/app/services/annotations/Neo4jAnnotations.scala
frontend/src/js/components/workspace/WorkspaceSummary.tsx
frontend/src/js/components/workspace/Workspaces.tsx

This PR updates the query for deleting workspace in order to allow the admins to delete a public workspace. 
Also on the UI, the delete button is only enabled if the user is admin and the workspace is public, or if the user is the owner of the workspace. 
This was tested locally and in playground. In playground, I asked my colleague to create a workspace and make it public. I then deleted that workspace as I am an admin user.

allow admin user to delete a public workspace

---

backend/app/extraction/TranscriptionExtractor.scala
backend/app/services/index/ElasticsearchResources.scala
backend/app/services/index/Index.scala
backend/app/utils/Whisper.scala

We had a bug in the transcript code - addDocumentTranscript is an async function but we were calling it once for the transcription then again for the translation without waiting for the first call to finish, resulting in unpredictable behaviour (often the transcription would overwrite the translation or vice versa).
This fixes that by writing both transcript and translated transcript in a single elasticsearch query
I've tested this locally with a file in german. Will test on playground just as soon as github actions finishes...

Fix transcription bug where a translation overwrites a transcription

---

backend/app/AppComponents.scala
backend/app/extraction/TranscriptionExtractor.scala
backend/app/services/Config.scala
backend/app/utils/AwsDiscovery.scala
backend/app/utils/Whisper.scala
backend/conf/application.conf

This pulls out the model we are using for whisper into a configuration parameter, which will allow us to change the model we are using by updating a value in parameter store and then redeploying giant. It also allows us to use different models on playground/dev/prod - which may be useful given that playground runs on less performant hardware to PROD, and often when testing stuff we care less about the quality of the transcription.
In future, we might want to make this even more configurable by using a feature switch
Tested on playground - I switched to using the `small` model and had a succesful trasnsription. 
To test in production edit the transcribe/modelFilename param in SSM
Based on some recent experiments, we might be able to get away with bumping the model to `small` from `base` - …

Set whisper model via configuration parameter

---

backend/conf/application.conf

Co-Authored-By: Philip McMahon <philip.mcmahon@guardian.co.uk>
- After a deployment of Giant, any browsers which had visited the site in the previous hour would see a "loading" page and would be unable to use the site.
- This was because the browser would load a cached version of `index.html` including a script tag with a url pointing to the old version of the javascript assets for the app, which no longer exists after the deployment.
- The browser requests this javascript file from the backend, it isn't found, and the [default response includes the contents of index.html](https://github.com/guardian/giant/blob/403ad2655c5721bf76c31858dc77231ca7cca71e/backend/app/controllers/frontend/App.scala#L24) which results in an error like `Refused to execute script because its MIME type …

Fix missing js asset bug

---

backend/app/AppComponents.scala
backend/app/commands/GetPagePreview.scala
backend/app/controllers/api/Previews.scala
backend/app/model/frontend/Node.scala
backend/app/utils/AllowFrameFilter.scala
backend/app/utils/RequestLoggingFilter.scala
backend/test/commands/CollectionSharingITest.scala
backend/test/controllers/api/EventsTest.scala
backend/test/controllers/api/ExtractorITest.scala
backend/test/controllers/api/WorkspaceSearchITest.scala
backend/test/controllers/api/WorkspaceSharingITest.scala
backend/test/controllers/api/WorkspacesITest.scala
backend/test/test/integration/Helpers.scala
backend/test/utils/IndexTestHelpers.scala
backend/test/utils/auth/AuthActionBuilderTest.scala
build.sbt
project/build.properties
project/plugins.sbt

Play 3.0 is the latest version of the play framework. There are two main benefits of upgrading:
- Play 3 [uses pekko instead of akka](https://www.playframework.com/documentation/3.0.x/General#How-Play-Deals-with-Akkas-License-Change), so we can remove the last traces of akka from our codebase and not risk angering the license gods
- Play 3 supports Scala 3
This was a pretty easy upgrade - just a few dependency bumps. The only 'code' change was I had to increase the length of the [play application secret ](https://www.playframework.com/documentation/3.0.x/ApplicationSecret)
We can't actually move to Scala 3 until we upgrade to elasticsearch 8 as elastic4s doesn't support elasticsearch 7 at the moment. 
Tested on playground.

Upgrade to version 3 of the Play Framework. Remove akka completely

---

frontend/src/js/App.js
frontend/src/js/components/UtilComponents/Token.tsx

Creates a page with a logged-in user's jwt token on it so that it can be scraped by [whistleflow-giant-login](https://github.com/guardian/whistleflow/pull/43).
To enable export from SecureDrop Workstation to Giant, we need SDW users to be able to log in to Giant in a dedicated whistleflow-giant-login VM, and scrape their jwt token so that it can be used to authenticate against the Giant API to retrieve a list of their workspaces and to upload files.
This token is currently available on the [settings/about](https://giant.pfi.gutools.co.uk/settings/about) page but creating a dedicated page will reduce the risk that future changes to the about page break whistleflow.

Create API token page for whistleflow

---

build.sbt

This should resolve:
- https://security.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-6094942
- https://security.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-6097492
- https://security.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-6097493
Tested on playground, logs still appeared to be working.

Bump logback to 1.4.14 to resolve various vulnerabilities

---

backend/app/AppComponents.scala
backend/app/commands/GetPagePreview.scala
backend/app/controllers/api/Previews.scala
backend/app/utils/AwsDiscovery.scala
backend/app/utils/RequestLoggingFilter.scala
backend/app/utils/WorkerControl.scala
backend/conf/application.conf
build.sbt
scripts/cluster-setup.sh

I noticed that when you run giant locally it starts logging this over and over again:
```
[WARN] 2023-12-18 10:47:27 GMT - org.apache.pekko.remote.artery.InboundHandshake$$anon$2 - application-pekko.actor.default-dispatcher-7 - Dropping Handshake Request from [pekko://application@localhost:1234#-6954875545553276590] addressed to unknown local address [pekko://pfi@localhost:1234]. Local address is [pekko://application@localhost:1234]. Check that the sending system uses the same address to contact recipient system as defined in the 'pekko.remote.artery.canonical.hostname' of the recipient system. The name of the ActorSystem must also match.
```
This is because of some bits and pieces missed when I removed Akka here https://github.com/guardian/giant/pull/180. This PR finishes the …

Tidy up akka removal

---

frontend/src/js/components/workspace/Workspaces.tsx

This adds two new context menu options to the workspace view in giant - 'Copy file name' and 'Copy file path' 
They look like this:
https://github.com/guardian/giant/assets/3606555/c4064d2f-545a-4f2d-a225-4023ed1d56db
Tested on playground and locally. There's a recursive function used to generate the file path, maybe it should have some tests? We actually don't appear to have _any_  client side tests in giant so that feels a bit of a stretch

Add copy to clipboard option to workspace context menu

---

riff-raff.yaml

As part of my 10% time I started upgrading elasticsearch to version 8. Whilst this is in progress (currently only on the playground stack) I need to disable this auto AMI update step, otherwise it will keep reverting the elasticsearch stack back to using an AMI running elasticsearch 7.

Disable elasticsearch AMI update

---

frontend/src/js/components/viewer/DownloadModal.js

This PR does the following:
- Fixes the extractedText download. the actual text is within the contents field within the text object. The existing code was trying to get the text string from the text itself. 
- Fixes the transcript download. The transcript download was added as a new download type so that depending on which transcript language the user picks, it would download the relevant language text file.

fix transcript and extractText download

---

backend/app/services/ElasticsearchSyntax.scala
backend/app/services/index/ElasticsearchPages.scala
backend/app/services/index/ElasticsearchResources.scala
backend/app/services/index/SearchContext.scala
backend/app/services/table/Table.scala
backend/test/test/integration/DockerElasticsearchService.scala
build.sbt
docker-compose.yml

Currently on Giant we are in a bit of a messy state. We're running version 7.17.9 of elasticsearch in production, but using version 7.9.1 of the elastic4s SDK. This PR resolves that.
This PR includes many of the changes initially made in https://github.com/guardian/giant/pull/187 - once it's merged https://github.com/guardian/giant/pull/187 should contain many fewer code changes
Changes included:
- Bumping the version of elasticsearch being used to run giant locally in docker-compose.yaml and the version used to run integration tests
- The way objectfields works has changed, leading to a small syntax change all over the place. It was hard to track down what had happened here but I eventually spotted this  [random bit of markdown](https://github.com/sksamuel/elastic4s/blob/67ff0c23aa9057d9b …

Upgrade elasticsearch sdk to version 7.17

---

backend/app/services/index/ElasticsearchPages.scala
backend/app/services/index/ElasticsearchResources.scala
backend/test/test/integration/DockerElasticsearchService.scala
build.sbt
docker-compose.yml

(Draft PR pending upgrade to ES8)
Following from https://github.com/guardian/giant/pull/190 This PR drags giant's elasticsearch code into the future, ready to support elasticsearch 8.
Key changes:
- version number bumps in build.sbt, docker-compose, elasticsearch docker service
- Replacing [deprecated updateByQuery](https://github.com/sksamuel/elastic4s/blob/83162ceb97be3e023f7644fce637e2da0678896c/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/api/UpdateApi.scala#L11)
Tested locally and on playground. Make sure you have run https://github.com/guardian/giant/pull/190 (now merged into main) locally before trying this as you need your local DB to already be on 7.17 to work
Deploying on PROD:
- ideally it would be good to use rest compatability mode …

Upgrade elasticsearch SDK to version 8.11

---

riff-raff.yaml

This PR is reverting the change that was done in https://github.com/guardian/giant/pull/184 but instead of `investigations-elasticsearch-7-arm64` it uses the `investigations-elasticsearch-8-arm64` recipe in amigo. 
We have already updated the elasticsearch version in all giant elasticsearch instances. And we have also updated the elasticsearch version in giant code base through https://github.com/guardian/giant/pull/187

add elasticsearch ami update with version 8

---

docker-compose.yml

Following the upgrade to ES8 #187  this setting is no longer valid

Remove deprecated bootstrap.system_call_filter setting

---

build.sbt

For ages we've had an issue where after a deployment any user who had recently used Giant would see a loading screen forever the next time they went to Giant. They would need to do a hard refresh after each deployment to get around the issue.
We worked out that this was a caching problem where the browser was loading a cached version on `index.html` which contained a script tag pointing to the old js bundle which, after the last deployment, no longer existed.
In #179 we added cache control header `no-cache` to the response when `index.html` is requested, which seemed to fix the issue for a while.
The `no-cache` header made it so that the server would revalidate on each request that the client's [Etag header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) matched that of …

Fix js caching issue

---

build.sbt

Upgrades to latest v1 of aws sdk - fix for https://security.snyk.io/vuln/SNYK-JAVA-SOFTWAREAMAZONION-6153869
Compiled locally, running snyk GHA shows vulnerability now gone.

Upgrade to latest aws sdk 1.12.643 due to snyk vulnerability

---

backend/app/commands/CreateIngestion.scala
backend/app/commands/IngestFile.scala
backend/app/controllers/api/Collections.scala
backend/app/services/manifest/Manifest.scala
backend/app/services/manifest/Neo4jManifest.scala
backend/conf/routes
frontend/src/js/components/Uploads/UploadFiles.tsx
frontend/src/js/components/Uploads/UploadTarget.ts
frontend/src/js/services/CollectionsApi.ts
frontend/src/js/util/auth/authUploadWithProgress.ts

This PR adds a new api endpoint to upload files so that it would not create new nodes if the file already exists.
- expects a new header `X-PFI-Ingestion-Name`
- using the file fingerprint, checks if same file already exists in the same workspace path
- reprocess the file if already exists
- if file doesn't already exist, it checks if there's already an ingestion with same name as retrieved from header `X-PFI-Ingestion-Name`
- If ingestion doesn't already exist, it creates ingestion, otherwise it uses the existing ingestion
- It processes the ingest file 
As can be seen in the video when the same file is uploaded in a workspace path that already has that file, file is reprocessed. But if that file is uploaded into a different path of the same workspace, the file upload does occur. …

reprocess instead of upload if uploaded file already exist

---

postgres/cdk/lib/giant.ts

We'll use [DevX managed RDS backups](https://github.com/guardian/aws-backup) which have tighter access control rather than automated backups (todo: remove the old backup config).
Tested on CODE - tags have been added.

Enable RDS backups with AWS Backup

---

postgres/cdk/lib/giant.ts

Removing legacy automated backup settings to prevent cloudformation drift, as they are now handled by aws-backups

Yield control of backups to aws backup

---

.github/workflows/postgres-build.yml

- Follow directions in actions-riff-raff to upgrade from version 2 to 4.
- [v2 to v3](https://github.com/guardian/actions-riff-raff/releases/tag/v3.0.0)
- [v3 to v4](https://github.com/guardian/actions-riff-raff?tab=readme-ov-file#migrating-from-v3-to-v4)
v4 avoids the need for configure-aws-credentials which stores aws credentials in an environment variables, allowing other, possibly malicious, actions to access them.

Upgrade to actions-riff-raff v4

---

build.sbt

Upgraded to `postgresql` to `42.7.2` due to the SQL ingestion vulnerability [SNYK-JAVA-ORGPOSTGRESQL-6252740](https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-6252740)
Tested on CODE - see https://playground.pfi.gutools.co.uk/settings/my-uploads?currentWorkspace=all

fix SNYK-JAVA-ORGPOSTGRESQL-6252740 by upgrading postgresql

---

riff-raff.yaml

We can save some money and hopefully boost performance by moving to graviton instances. Once testing is complete on a graviton AMI, this PR will tell riffraff to use a graviton ami when deploying giant
Depends on https://github.com/guardian/investigations-platform/pull/481

Use arm64 ami

---

backend/app/extraction/archives/ZipExtractor.scala
backend/app/extraction/email/olm/OlmEmailExtractor.scala
build.sbt

Upgrading `commons-compress` to fix https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-6254296
(previously tried upgrading `tika` but is uses conflicting versions of `jackson-databind` to `play` which results in a runtime error ([tika uses 2.15.2](https://mvnrepository.com/artifact/org.apache.tika/tika-parsers-standard/2.9.1), [play uses 2.14.3](https://mvnrepository.com/artifact/org.playframework/play_3/3.0.2))
Deployed and tested to CODE

upgrading tika to 2.9.1 to fix SNYK-JAVA-ORGAPACHECOMMONS-6254296

---

backend/app/controllers/api/PagesController.scala
backend/app/controllers/api/Resource.scala
backend/app/controllers/api/Search.scala
backend/app/model/frontend/Chip.scala
backend/app/model/index/SearchParameters.scala
backend/test/controllers/api/WorkspaceSearchITest.scala
frontend/src/js/components/UtilComponents/InputSupper/Chip.js
frontend/src/js/components/UtilComponents/InputSupper/index.js
frontend/src/js/components/workspace/Workspaces.tsx

- Introduces a new "workspace folder" Chip (documented here [Search in Giant](https://docs.google.com/document/d/1uejYdU7w5GJpmg9R2u-Wi6qr1YfSg7bWHRRazDwHjUU/edit)) which allows a user to search inside a specific folder in a workspace.
- at the moment, a "workspace folder" chip can be removed but not created or edited
- Adds a "search in folder" item to the context menu when a user right clicks on a folder in the workspace view. This links to the search view with a "workspace folder" chip pre-populated.
- Changes to the /search endpoint to handle this new chip type. Most of the logic to filter by the blobs in a folder was introduced in https://github.com/guardian/pfi/pull/811 and is repurposed here.
Users will be able to search inside a folder inside a workspace.
- We could add the …

Search in workspace folder

---

backend/app/controllers/api/Search.scala

Adds a log with user email when they perform a workspace search
We would like to know how much this new feature is used

Add workspace search log

---

backend/app/utils/auth/providers/PanDomainUserProvider.scala
build.sbt

Bump to latest version of `pandomain-auth` - this is apparently supposed to be seamless and not as multiple-major-versiony as it looks. This could potentially help us with an upgrade of `bouncycastle` as it is in `pandomain-auth`'s dependency tree, which for which there is a high vulnerability with our current version (1.70).
Tested on CODE

Upgrading pan-domain-auth

---

.github/workflows/build.yml

As part of this PR https://github.com/guardian/giant/pull/220 we updated the build action config to use an arm based runner but the name of the runner was `4core-ubuntu-latest-arm-coverdrop`. We then created another runner without the coverdrop in its title, and this PR is the change in build config to use the new runner `4core-ubuntu-latest-arm-giant`

update build runner to the giant one

---

frontend/src/setupProxy.js

The version upgrade of `http-proxy-middleware` in this PR https://github.com/guardian/giant/pull/222 was causing issues in local run and couldn't proxy the requests to the correct target. This is because of a breaking change in V3 as explained in https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md#removed-requrl-patching  that When proxy is mounted on a path, this path should be provided in the target. 
```
// before
app.use('/user', proxy({ target: 'http://www.example.org' }));
// after
app.use('/user', proxy({ target: 'http://www.example.org/user' }));
```

fix the breaking change in http-proxy-middleware upgrade

---

backend/public/third-party/pdf.worker.min.js
frontend/package-lock.json
frontend/package.json
frontend/src/js/components/PageViewer/PdfHelpers.ts
frontend/src/js/components/viewer/PageViewer/pageViewerPdf.ts

This PR is upgrading the version of pdfjs-dist  from 3.0.279 to 4.2.67. There were some api changes in pdfjs-dist that was affecting failures. 
- [api-minor] Combine the textContent/textContentStream parameters in https://github.com/mozilla/pdf.js/pull/15779
- [api-minor] Remove the disableCombineTextItems option in https://github.com/mozilla/pdf.js/pull/16234
- The pdfjs-dist build used to generate `pdf.worker.min.js` but now it's generating it in mjs `pdf.worker.min.mjs`
There were so many other changes in pdfjs-dist but they don't seem to affect our code. 
I tested this locally and also in playground by uploading pdfs and viewing them in the UI. The pdfs are all rendered successfully.

upgrade pdfjs-dist from 3.0.279 to 4.2.67

---

frontend/package-lock.json
frontend/package.json

This PR upgrades d3 library. The only usage of this library is in https://github.com/guardian/giant/blob/main/frontend/src/js/components/EmailBrowser/Timeline.js#L5 
I tested this locally and the email threads are rendering correctly. 
We need to upgrade d3-colour to 3.1.0 due to vulnerability https://github.com/guardian/giant/security/dependabot/2
But d3 library depends on d3-colour and to be able to update d3-colour we had to upgrade d3 from v4 to v7.

upgrade d3 from 4.13.0 to v7.9.0

---

.tool-versions
build.sbt

Upgrades jackson to version 2.15.4 which fixes a Denial of Service vulnerability in the current version

Upgrade jackson to 2.15.4

---

docker-compose.yml
scripts/start-backend.sh

All developers on the team are using apple silicon.This change makes the arm version of the neo4j image the default, which means we'll be able to run `docker-compose up` without having to set the NEO4J_OVERRIDE environment variable 
Tested on my local machine. This should have no impact on playground/prod

Make the arm64 neo4j container the default

---

frontend/src/js/util/resourceUtils.ts

Bumps the max number of children in a tree viewer to 2000.
We have an important workspace with too many entries per directory.

attempt to render 2000 children in workspace tree

---

build.sbt
project/plugins.sbt

This upgrades the play framework sbt plugin. This might resolve https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538 but who knows with jackson vulnerabilities. At the very least, it's a patch version so shouldn't do much harm.

Bump play version from 3.0.0 to 3.0.5

---

backend/app/AppComponents.scala
backend/app/utils/auth/providers/PanDomainUserProvider.scala
backend/test/utils/auth/providers/PanDomainUserProviderTest.scala
build.sbt

This upgrades Panda from v3 to v7, increasing security by allowing us to use key-rotation as introduced with guardian/pan-domain-authentication#150.
I'm very happy to do a walkthrough of the changes with the reviewer if that helps!
* Panda v5
* https://github.com/guardian/pan-domain-authentication/pull/147 removed the old `PublicKey` & `PrivateKey` classes in our `com.gu.pandomainauth` package, in favour of using the existing `java.security` classes. To create instances of those classes, we can use the `SettingsReader.{privateKeyFor, publicKeyFor}` methods.
* Panda v6:
* https://github.com/guardian/pan-domain-authentication/pull/152 means the `CookieUtils.generateCookieData()` method now communicates errors with `CookieResult` values containing `CookieIntegrityFailure`, rather than …

Upgrade to Panda v7 - support key rotation

---

backend/app/extraction/ExternalTranscriptionExtractor.scala

Following https://github.com/guardian/transcription-service/pull/123 these are now required fields 
Deploy to playground, verify that transcription works

Add engine and diarize fields to TranscriptionJob

---

frontend/src/js/components/viewer/DownloadModal.js

Fixes type error in DownloadModal component when props.resource.text is undefined
Testing in prod

Hotfix type error in download modal

---

backend/conf/application.conf
frontend/src/js/components/Uploads/UploadFiles.tsx

This reverts commit ee6ce182c16da6bd18a871761bdfca7b548bc76c - when messing around with the built in browser vscode I accidentally committed the change to main. oops! I'll enable branch protection now...

Revert "Bump max upload size via ui to 300mb"

---

backend/app/model/annotations/Workspace.scala

This fixes a bug where the giant workspace API uses the 'added on' date for the 'size' field, resulting in seemingly astronomical reported file sizes by the workspace API
Size definitely is a filed in neo4j, I'll just test on playground first...

Return size rather than addedOn date in size field of workspace API

---

frontend/src/js/components/workspace/Workspaces.tsx

Increased default name, added by, and processing stage column widths
It didn't look to me like this widths had any constraints on them (e.g. they have to fit in a div of a specific width) but I'm me so please check I'm not wrong.

Increase default workspace column widths

---

frontend/src/js/components/viewer/StatusBar.js

For the right and left arrrows at the bottom of the document view (in text views such as transcripts, OCRs, etc), these buttons take you to the prev/next results for the search that was performed to get to the current document; they are not next results of searches performed within the document.

Text view status bar: clarify purpose of prev and next

---

backend/app/services/manifest/Neo4jManifest.scala

https://github.com/guardian/giant/pull/275 introduced a bug where if you send a file (blob) for reprocessing that doesn't have an EXTRACTION_FAILURE relation with an external extractor then an error is returned every time. This resolves that by changing the error condition - if we haven't deleted any relations then we don't have to worry about how many counters were reset.
Reprocessing is completely broken on PROD right now, this will fix that

Don't fail external reprocess job if there are no errors to reprocess.

---

backend/app/extraction/ExternalTranscriptionExtractor.scala
backend/app/extraction/ExternalTranscriptionWorker.scala
backend/app/extraction/TranscriptionExtractor.scala
backend/app/utils/Whisper.scala

This PR gets giant to make use of the new 'combined output' file added to the transcription service output in https://github.com/guardian/transcription-service/pull/167 
As well as simplifying some of our types (no longer need for the 'bucketurls' types with srt/txt/json), this change will make it easy to start storing other output types from the transcription tool in giant. In particular we're interested in subtitle formats, which will enable us to add subtitles to giant's video player and to see the timecode of matches for giant searches. 
I've tested this by deploying to playground, it's a bit of an 'all or nothing' change so I am fairly confident that it will work.

Use combined transcript file from transcription service

---

backend/app/extraction/ExternalTranscriptionExtractor.scala

We've been having some problems with our whisper.cpp transcription service, so let's switch giant to using whisperx.
Deployments steps:
- Deploy this change
<hope that no audio/video files get uploaded to giant here>
- update the param /pfi/pfi-giant/rex/transcribe/transcriptionServiceQueueUrl to the correct queue
Tested on playground, it seems to work - although there's a 12 minute startup penalty for the whisperx runners unfortunately

Set external transcription engine to whisperx

---

backend/app/extraction/ExternalTranscriptionWorker.scala

I think the external transcription extractor is too chatty - we currently get 3 log lines every time it polls the queue, even when there are no messages fetched. 
This cuts down those log lines.

Don't log when no messages fetched in ExternalTranscriptionWorker

---

backend/app/model/annotations/Workspace.scala
backend/app/services/annotations/Neo4jAnnotations.scala
backend/test/services/index/SearchContextTest.scala
frontend/src/js/components/workspace/Workspaces.tsx
frontend/src/js/types/Workspaces.ts
frontend/src/js/util/workspaceUtils.fixtures.ts

- expose/calculate `descendantsLeafCount`,`descendantsNodeCount, `descendantsProcessingTaskCount`, `descendantsFailedCount` when building the workspace contents for API responses
- use `descendantsLeafCount` and `descendantsNodeCount` to show subtle (smaller & grey) totals of descendant files & folders on all nodes of the tree 
- use `descendantsProcessingTaskCount` and `descendantsFailedCount` to show total counts of descendant 'in progress tasks' and 'failures' in the `Processing Stage' column for all nodes (which have descendant in progress / failed) tasks AND display the spinner icon on all the parent nodes of in progress tasks (so people can easily find nested jobs)
Navigate some workspaces and see this extra detail (ideally ones, with some in-progress jobs, noting the extra detail …

bubble up counts of files, folders, processing tasks and failures up the tree of nodes

---

backend/app/services/manifest/Neo4jManifest.scala

This resolves a bug in https://github.com/guardian/giant/pull/290 - we need to actually return the owner from the neo4j query.
I noticed this issue when trying to understand why reprocessing (right click>>reprocess) was failing when I tried to reprocess a file uploaded to a workspace by someone else. This error would be thrown:
Unknown Failure: org.neo4j.driver.v1.exceptions.value.NotMultiValued: NULL is not a keyed collection
at org.neo4j.driver.internal.value.ValueAdapter.get(ValueAdapter.java:358)
at model.user.DBUser$.fromNeo4jValue([DBUser.scala:20](https://github.com/guardian/giant/blob/cdf12737262fa40866e15725da405b74d3df2350/backend/app/model/user/DBUser.scala#L20))
at services.manifest.Neo4jManifest.$anonfun$getWorkspacesForBlob$3([Neo4jManifest.scala:112](https://github.com/guard …

Return owner in getWorkspacesForBlob
