guardian/giant

- backend/app/AppLoader.scala
- backend/app/utils/AwsDiscovery.scala
Ronseal. This helps us investigate problems by filtering down the logs.
> Log stack, app, stage and instanceId in AWS

- frontend/src/stylesheets/components/_document.scss
Ronseal.
Get rid of the sloped highlighting, since it looks very silly on large highlights.
> remove cute slanted highlighting

- .github/workflows/snyk.yml
This adds a snyk GitHub Actions workflow to generate accurate snyk dependency reports for the Giant Scala project.
> Add snyk workflow

- .github/workflows/snyk.yml
This PR adds Node to the Snyk workflow.
> Add node to snyk

- cli/README.md
This was a bit of a faff to work out so I wrote it all down like a pro
> Add some docs for running pfi-cli locally

- backend/app/controllers/api/PagesController.scala
- backend/conf/routes
- frontend/src/js/components/PageViewer/Controls.module.css
- frontend/src/js/components/PageViewer/Controls.tsx
- frontend/src/js/components/PageViewer/FindInput.module.css
- frontend/src/js/components/PageViewer/FindInput.tsx
- frontend/src/js/components/PageViewer/Page.tsx
- frontend/src/js/components/PageViewer/PageCache.ts
- frontend/src/js/components/PageViewer/PageHighlight.module.css
- frontend/src/js/components/PageViewer/PageHighlight.tsx
- frontend/src/js/components/PageViewer/PageViewer.module.css
- frontend/src/js/components/PageViewer/PageViewer.tsx
- frontend/src/js/components/PageViewer/VirtualScroll.tsx
- frontend/src/js/components/UtilComponents/InputSupper/InlineInput.js
- frontend/src/js/components/UtilComponents/InputSupper/index.js
Adds a second control, non-editable, to navigate between main search highlights
https://user-images.githubusercontent.com/5122968/176723786-18bc15d2-95f2-4d48-a446-4d6f2895bac7.mov
> Add search highlighting and nav

- .tool-versions
- scripts/start-backend.sh
> Start docker and choose Java versions automatically

- backend/app/commands/DeleteResource.scala
We use elasticsearch to determine what blobs are in a collection.
This means that once we've deleted from elasticsearch, the blob no longer exists from the perspective of a "delete collection" request.
So we should delete from elasticsearch last, so that if any of the other operations fail (delete from neo4j, delete from S3), we are still able to clear things up by restarting the delete collection operation.
> Delete from elasticsearch last

- backend/app/services/index/Pages2.scala
We get a lot of Giant alarms fired from requests to get a page that doesn't appear to exist in S3 or elasticsearch.
[Here are some relevant logs](http://localhost:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-4d,to:now))&_a=(columns:!(message),filters:!(),index:d2720940-0e30-11eb-a809-5706b391daea,interval:auto,query:(language:kuery,query:'level:%22ERROR%22%20and%20(%22head%20of%20empty%20list%22%20OR%20%22not%20found%22)'),sort:!())) (you need the usual VPN tunnel)
Typically the errors happen in pairs, as the same page is requested from S3 and elasticsearch, and it's not in either place.
The S3 error is gracefully handled as a `NotFoundFailure`.
But the elasticsearch lookup involves a `head` call which causes an exception to escape when it can't …
> Safely check whether a page is present in elasticsearch

- backend/app/extraction/MetadataEnrichment.scala
- backend/app/services/Tika.scala
- build.sbt
To fix security vulnerabilities
> Upgrade tika to v2

- common/src/main/scala/model/Language.scala
co-authored with @philmcmahon 
This PR is adding support for Spanish language in Giant. 
Tested locally by running the cli, and also in playground the ingestion worked fine
> Support spanish language

- backend/app/utils/auth/providers/PanDomainUserProvider.scala
- backend/test/utils/auth/providers/PanDomainUserProviderTest.scala
The new standard for Guardian gsuite emails are lower case, although previously they might have been title case eg `Firstname.Lastname@theguardian.com`. We will switch to using lower case in Giant for all email usernames, which means authenticating against the downcased email from the panda cookie. We have a couple of users who are title case in the db which we will manually remove and re-add in their lowercase form. 
We will need to test with a "title cased user" logging in successfully against their lowercase email as exists in Giant.
> Authenticate against the downcased email coming in from panda cookie

- backend/app/services/observability/PostgresClient.scala
This PR fixes the issue where the observability dashboard was showing all the statuses from all ingestions for a specific file. This change, would only show the statuses that are relevant for that particular ingestion. 
I also added an order by, so that when the page is loaded for the first time, the data is ordered with most recent at the top.
> only show statuses relevant to the ingest

- backend/app/extraction/tables/ExcelTableExtractor.scala
This PR fixes a bug in `ExcelTableExtractor` where the logic for getting the row data wasn't being evaluated and therefore `cellReference`  was staying null. This was causing an unhandled `java.lang.NullPointerException` exception.  
Tested in playground and locally
> Fix ExcelTableExtractor NullPointerException

- backend/app/services/WorkerScheduler.scala
This PR is wrapping the worker logic in a try catch in order to handle the errors that couldn't be handled through the Attempt failure case. 
E.g. we were experiencing error from the neo4j driver `org.neo4j.driver.v1.exceptions.ServiceUnavailableException`, which put the worker schedular in a failed state and stopped triggering the worker on that instance. 
In Giant we are using the Attempt wrapper that can contain specific errors in the form of Failure. But if there's any error thrown that's not handled and wrapped in a Failure, it won't be recovered by the `recoverWith` in the WorkerScheduler and thus, the actorSystem schedular will stop working and triggering the worker. 
It might be good if this implementation is enhanced in the future and we use a proper messaging system such as …
> handle unhandled exceptions in worker

- docs/04-elasticsearch-mapping.md
Adds some basic documentation on updating the elasticsearch mapping, something we puzzled over for a while yesterday.
> Document elasticsearch mapping updates

- frontend/package-lock.json
Relocked after we got out of sync
Has now disappeared from snyk after running the GHA
> Relocking the lock file to fix https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6141137

- frontend/package-lock.json
- frontend/package.json
This PR upgrades @elastic/charts from `66.1.0` to `66.1.1`
tested locally
> upgrade elastic/charts to update d3-color sub dependancy

- scripts/start-frontend.sh
> Fix start-frontend.sh

- frontend/src/js/util/resourceUtils.ts
These days we've got lovely apple silicone, maybe the browser can handle trees with 3000 things in them?! 
Find a folder with > 2000 things in it, try open it...
> Set MAX_NUMBER_OF_CHILDREN of workspace view to 3000
